language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
#matrix:
#    allow_failures:
#        - julia: nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("ImageDraw")'
    - julia -e 'import Pkg; Pkg.test("ImageDraw", coverage=true)'
after_success:
    - if [ $TRAVIS_OS_NAME = "linux" ]; then
         julia -e 'cd(Pkg.dir("ImageDraw")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
      fi
#   - julia -e 'Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl")'
#   - julia -e 'cd(Pkg.dir("ImageDraw")); include(joinpath("docs", "make.jl"))'
